GET http://localhost:3000/books

###

POST http://localhost:3000/books
Content-Type: application/json

{
  "name": "Cracking the coding interview 5",
  "author": "Unknow",
  "isbn": "0984782869",
  "numberOfPages": 1000,
  "bookEdition": "first",
  "bookFormat": "hardcopy"
}